// pages/blog/index.tsx
import styled from '@emotion/styled';
import tw from 'twin.macro';

import { Blog } from '~/components';
import { Layout } from '~/layouts';
import { deserialisePost } from '~/lib';
import { getPosts } from '~/lib/build';

import type { GetStaticPropsResult } from 'next';

import type { Posts } from '~/types';

interface BlogProps {
	posts?: Posts;
}

const Container = styled.div(tw`
	mt-24 sm:mt-16 mb-20 mx-4 sm:mx-6 lg:mb-28 lg:mx-8
`);

const Content = styled.div(tw`
	relative max-w-6xl mx-auto
`);

const PostsContainer = styled.p(tw`
	max-w-lg \
		mt-4 lg:mt-12 mx-auto \
		grid gap-5 grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 sm:max-w-none
`);

export async function getStaticProps(): Promise<GetStaticPropsResult<BlogProps>> {
	const posts = await getPosts();

	return {
		props: {
			posts,
		},
	};
}

export default function _Blog({ posts }: BlogProps) {
	if (!posts || posts.length <= 0) return <Blog.Error />;

	const deserialisedPosts = posts.map((post) => deserialisePost(post));
	const latestPost = deserialisedPosts.shift();

	return (
		<Layout.Default seo={{ title: 'nuro ─ blog ─ all' }}>
			<Container>
				<Content>
					<Blog.Latest post={latestPost} />
					<PostsContainer>
						{deserialisedPosts.map((post, i) => (
							<Blog.Post key={i} post={post} index={i} />
						))}
					</PostsContainer>
				</Content>
			</Container>
		</Layout.Default>
	);
}

// src/pages/blog/index.vue
<template>
	<div class="content">
		<div class="relative max-w-6xl mx-auto">
			<PostLatest :post="latestPost" />
			<div class="posts">
				<PostCard v-for="(post, i) in posts" :key="i" :post="post" :index="i" />
			</div>
		</div>
	</div>
</template>

<script lang="ts" setup>
import { useHead } from '@vueuse/head';

import { usePosts } from '~/consumables';

useHead({
	title: 'nuro ─ blog',
});

const { latestPost, posts } = usePosts();
</script>

<style lang="postcss" scoped>
.content {
	@apply relative \
		pt-24 sm:pt-16 pb-20 px-4 sm:px-6 lg:pb-28 lg:px-8;

	.title {
		@apply text-3xl sm:text-4xl font-extrabold \
			text-gray-900 dark:text-white \
			tracking-tight;
	}

	.subtitle {
		@apply mt-3 sm:mt-4 \
			text-md font-medium \
			text-gray-400;
	}

	.posts {
		@apply max-w-lg \
			mt-4 lg:mt-12 mx-auto \
			grid gap-5 grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 sm:max-w-none;
	}
}
</style>
