// src/components/Blog/X/XFigure.component.tsx
import Image from 'next/image';

interface XFigureProps {
	alt?: string;
	caption?: string;
	src: string;
}

export function XFigure({ alt, caption, src }: XFigureProps): JSX.Element {
	return (
		<figure>
			<Image
				alt={alt ?? caption}
				className="rounded-3xl object-cover select-none hover:shadow-xl"
				draggable={false}
				height="100%"
				layout="responsive"
				src={src}
				width="100%"
			/>
			<figcaption>{alt ?? caption}</figcaption>
		</figure>
	);
}

// src/components/blog/x/X-Figure.vue
<template>
	<figure>
		<img
			class="w-full rounded-3xl object-cover select-none hover:shadow-xl"
			:src="src"
			:alt="alt ?? caption"
			:draggable="false"
		/>
		<figcaption v-if="caption">
			{{ caption }}
		</figcaption>
	</figure>
</template>

<script lang="ts" setup>
import { defineProps } from 'vue';

defineProps<{
	alt?: string;
	caption?: string;
	src: string;
}>();
</script>
