// src/pages/status.tsx
import { Layout } from '~/layouts';
import { Status } from '~/components';

export default function StatusPage(): JSX.Element {
	return (
		<Layout.Default seo={{ title: 'nuro ─ status' }}>
			<div className="flex flex-grow min-h-screen pt-16 pb-12">
				<div className="flex-grow flex flex-col justify-center max-w-sm sm:max-w-lg w-full mx-auto px-0 sm:px-16">
					<Status.Widget />
				</div>
			</div>
		</Layout.Default>
	);
}

// src/pages/status.vue
<template>
	<ThemeButton />
	<div class="content">
		<div class="sm:mx-auto sm:w-full sm:max-w-md">
			<StatusWidget />
		</div>
	</div>
</template>

<style lang="postcss" scoped>
.content {
	@apply min-h-screen flex flex-col justify-center items-center py-12 sm:px-6 lg:px-8 \
		text-sm text-gray-600 dark:text-gray-100;
}
</style>
