// src/components/blog/x/X-Figure.vue
<template>
	<figure>
		<img
			class="w-full rounded-3xl object-cover select-none hover:shadow-xl"
			:src="src"
			:alt="alt ?? caption"
			:draggable="false"
		/>
		<figcaption v-if="caption">
			{{ caption }}
		</figcaption>
	</figure>
</template>

<script lang="ts" setup>
import { defineProps } from 'vue';

defineProps<{
	alt?: string;
	caption?: string;
	src: string;
}>();
</script>

// components/Blog/X/XFigure.component.tsx
import styled from '@emotion/styled';
import tw from 'twin.macro';

interface XFigureProps {
	alt?: string;
	caption?: string;
	src: string;
}

const Image = styled.img(tw`
	w-full \
	rounded-3xl object-cover select-none hover:shadow-xl
`);

export function XFigure({ alt, caption, src }: XFigureProps) {
	return (
		<figure>
			<Image src={src} alt={alt ?? caption} draggable={false} />
			{caption && <figcaption>{caption}</figcaption>}
		</figure>
	);
}
