// src/App.vue
<template>
	<router-view />
</template>

<script lang="ts" setup>
import { computed } from 'vue-demi';
import { onKeyDown } from '@vueuse/core';
import { useHead } from '@vueuse/head';

import { colors } from '~/utils';
import { isDark, toggleTheme } from '~/hooks';

onKeyDown('t', () => toggleTheme());

useHead({
	meta: [
		{
			name: 'theme-color',
			content: computed(() => (isDark.value ? colors.gray[900] : colors.gray[50])),
		},
	],
});
</script>

<style lang="postcss">
@use "~inter-ui/default" with (
  $inter-font-display: swap,
  $inter-font-path: '~inter-ui/Inter (web)'
);
@use "~inter-ui/variable" with (
  $inter-font-display: swap,
  $inter-font-path: '~inter-ui/Inter (web)'
);
@include default.all;
@include variable.all;

html {
	@apply antialiased \
		bg-gray-50 text-gray-500 dark:text-gray-400 \
		transition ease-in-out duration-300;
	font-family: 'Inter', 'system-ui';
}
html.dark {
	@apply bg-gray-900;

	* {
		--tw-ring-offset-color: #0c0e10;
	}
}

*::selection {
	@apply bg-white \
		text-primary-500;
}

@supports (font-variation-settings: normal) {
	html {
		font-family: 'Inter var', 'system-ui';
	}
}

#nprogress .bar {
	@apply h-1 bg-gray-800 dark:bg-white;
}

code[class*='language-'],
pre[class*='language-'] {
	text-shadow: none;
}

.token.operator,
.token.entity,
.token.url,
.language-css .token.string,
.style .token.string {
	background: none;
}
</style>

// pages/_app.tsx
import Head from 'next/head';
import NProgress from 'nprogress';
import Router from 'next/router';
import tw, { GlobalStyles as TailwindStyles } from 'twin.macro';
import { AppProps } from 'next/app';
import { css, Global as EmotionStyles } from '@emotion/react';
import { ThemeProvider } from 'next-themes';
import { Toaster } from 'react-hot-toast';

import 'inter-ui/inter.css';
import 'nprogress/nprogress.css';

import TailwindCSS from '~/tailwind.config';
import { useAnalytics } from '~/lib';
import { Theme } from '~/types';

NProgress.configure({
	minimum: 0.3,
	easing: 'ease',
	speed: 800,
	showSpinner: false,
});

Router.events.on('routeChangeStart', () => NProgress.start());
Router.events.on('routeChangeComplete', () => NProgress.done());
Router.events.on('routeChangeError', () => NProgress.done());

const GlobalStyles = css`
	html {
		${tw`
			antialiased \
			bg-gray-50 \
			text-gray-500 dark:text-gray-400 \
			transition ease-in-out duration-300
		`}
		font-family: "Inter", "system-ui";

		&.dark {
			${tw`bg-gray-900`}

			* {
				--tw-ring-offset-color: #0c0e10;

				&::selection {
					${tw`bg-white text-primary-500`}
				}
			}
		}
	}

	*::selection {
		${tw`bg-gray-900 dark:bg-white text-white dark:text-primary-500`}
	}

	@supports (font-variation-settings: normal) {
		html {
			font-family: 'Inter', 'system-ui';
		}
	}

	#nprogress .bar {
		${tw`h-1 bg-primary-500`}
	}
`;

export default function App({ Component, pageProps }: AppProps) {
	useAnalytics();

	return (
		<ThemeProvider attribute="class" defaultTheme={Theme.SYSTEM} themes={Object.values(Theme)}>
			<Head>
				<meta name="theme-color" content={TailwindCSS.theme.extend.colors.primary[500]} />
			</Head>
			<EmotionStyles styles={GlobalStyles} />
			<TailwindStyles />
			<Toaster />
			<Component {...pageProps} />
		</ThemeProvider>
	);
}
