// src/pages/index.vue
<template>
	<div class="content">
		<transition
			enter-active-class="transition duration-1000 delay-500 ease-in-out"
			enter-from-class="transform opacity-0"
			enter-to-class="transform opacity-100"
			leave-active-class="transition duration-1000 delay-500 ease-in-out"
			leave-from-class="transform opacity-100"
			leave-to-class="transform opacity-0"
		>
			<div v-show="title">
				<h1 class="title">
					<span class="text">
						Hey <span class="wave">👋</span> I'm Ben,
						<br />
						a <span class="pill"> developer </span>
					</span>
				</h1>
				<p class="description">
					Anim aute id magna aliqua ad ad non deserunt sunt. Qui irure qui lorem cupidatat
					commodo. Elit sunt amet fugiat veniam occaecat fugiat aliqua.
				</p>
			</div>
		</transition>
	</div>

	<client-only>
		<transition
			enter-active-class="transition duration-2000 ease-in-out"
			enter-from-class="transform opacity-0"
			enter-to-class="transform opacity-100"
			leave-active-class="transition duration-1000 ease-in-out"
			leave-from-class="transform opacity-100"
			leave-to-class="transform opacity-0"
		>
			<Background v-show="background" />
		</transition>
	</client-only>
</template>

<script lang="ts" setup>
import { onMounted, ref } from 'vue';
import { onKeyDown, useStorage } from '@vueuse/core';

const title = ref(false);
const background = ref(false);
const isAnimated = useStorage('animated-background', true);
onKeyDown('b', () => (background.value = !background.value));

onMounted(() => {
	title.value = true;
	setTimeout(() => {
		if (isAnimated) background.value = true;
	}, 1000);
});
</script>

<style lang="postcss" scoped>
.content {
	@apply h-screen flex flex-col justify-center items-center \
		text-center;

	.title {
		@apply text-gray-500 dark:text-white \
			text-5xl sm:text-6xl md:text-6xl lg:text-8xl \
			tracking-tight font-extrabold;

		.text {
			@apply block xl:inline \
				lg:mr-4;
		}

		.pill {
			@apply inline-flex \
				mt-8 lg:ml-2 lg:px-5 py-2 -pb-4 \
				bg-primary-500 bg-opacity-15 \
				backdrop-filter backdrop-blur-sm saturate-200 \
				text-primary-200 \
				rounded-2xl cursor-pointer;
		}

		* {
			&::selection {
				@apply bg-white \
					text-primary-500;
			}
		}
	}

	.description {
		@apply max-w-md \
			mt-4 md:mt-8 mx-auto \
			text-base text-gray-300 dark:text-gray-400 sm:text-lg md:text-xl md:max-w-3xl;
	}
}

/* Credit to: https://jarv.is/notes/css-waving-hand-emoji/ */
.wave:hover {
	@apply inline-block \
		transition ease-in-out duration-300;
	animation: wave 2.25s ease-in-out infinite;
	transform-origin: 70% 70%;
}
@keyframes wave {
	0% {
		transform: rotate(0deg);
	}
	10% {
		transform: rotate(14deg);
	}
	20% {
		transform: rotate(-8deg);
	}
	30% {
		transform: rotate(14deg);
	}
	40% {
		transform: rotate(-4deg);
	}
	50% {
		transform: rotate(10deg);
	}
	60% {
		transform: rotate(0deg);
	}
	100% {
		transform: rotate(0deg);
	}
}
</style>

// pages/index.tsx
import styled from '@emotion/styled';
import tw from 'twin.macro';
import { differenceInYears, isSameDay, isSameMonth } from 'date-fns';
import { Icon } from '@iconify/react';

import { Button, Event, Transition, Wave } from '~/components';
import { EventType, NavigationItemType } from '~/types';
import { Layout } from '~/layouts';
import { usePersistantState } from '~/lib';

import type { NavigationItem } from '~/types';

const Container = styled.div(tw`
	min-h-screen flex items-center justify-center \
	py-12
`);

const Content = styled.div(tw`
	max-w-md sm:max-w-lg md:sm:max-w-2xl lg:sm:max-w-3xl w-full space-y-8 \
	text-center
`);

const Title = styled.h1(tw`
	text-gray-500 dark:text-white \
	text-5xl sm:text-6xl md:text-6xl lg:text-8xl \
	tracking-tight font-extrabold
`);

const Description = styled.p(tw`
	max-w-xs \
	mt-4 md:mt-8 mx-auto \
	text-base text-gray-300 sm:text-lg md:text-xl md:max-w-3xl
`);

const LineBreak = styled.br(tw`
	hidden sm:block
`);

const Pill = styled.div(tw`
	inline-flex \
	mt-4 px-3 lg:px-5 py-2 md:pb-4 \
	bg-primary-500 bg-opacity-15 \
	backdrop-filter backdrop-blur-sm saturate-200 \
	text-primary-200 \
	rounded-2xl \
	transition ease-in-out duration-300 \
	focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-primary-500
`);

const Actions = styled.div`
	${tw`
		flex flex-col sm:flex-row items-center justify-center sm:space-x-4 space-y-4 sm:space-y-0 w-full \
		mt-8 sm:mt-4
	`}

	div {
		${tw`
			w-full sm:w-auto
		`}
	}
`;

const ActionIcon = styled(Icon)(tw`
	mr-3
`);

const ActionText = styled.span(tw`
	-mt-1 py-1
`);

const ACTIONS: Array<NavigationItem> = [
	{
		type: NavigationItemType.LINK,
		href: '/blog',
		icon: <ActionIcon icon="feather:edit-3" />,
		text: 'Blog',
	},
	{
		type: NavigationItemType.LINK,
		href: '/projects',
		icon: <ActionIcon icon="feather:copy" />,
		text: 'Projects',
	},
	{
		type: NavigationItemType.LINK,
		external: true,
		href: 'https://github.com/nurodev',
		icon: <ActionIcon icon="feather:github" />,
		text: 'GitHub',
	},
];

export default function HomePage() {
	const { animations: animations } = usePersistantState().get();

	const today = new Date();
	const birthday = new Date('1997-08-09');
	const age = differenceInYears(today, birthday);
	const isBirthday = isSameDay(today, birthday) && isSameMonth(today, birthday);

	const description = `I am a ${age} year old software engineer & games developer`;

	return (
		<Layout.Default>
			{isBirthday && <Event event={EventType.BIRTHDAY} />}
			<Container>
				<Content>
					{animations ? (
						<Transition duration={1000}>
							<Title>
								Hey <Wave>👋</Wave> I'm Ben, <LineBreak />a <Pill>developer</Pill>
							</Title>
						</Transition>
					) : (
						<Title>
							Hey <Wave>👋</Wave> I'm Ben, <LineBreak />a <Pill>developer</Pill>
						</Title>
					)}
					{animations ? (
						<Transition delay={500} duration={1000}>
							<Description>{description}</Description>
						</Transition>
					) : (
						<Description>{description}</Description>
					)}

					<Actions>
						{ACTIONS.map((action, index) => {
							if (action.type !== NavigationItemType.LINK) return null;

							if (!animations)
								return (
									<Button.Outline key={index} href={action.href}>
										{action.icon}
										<ActionText>{action.text}</ActionText>
									</Button.Outline>
								);

							return (
								<Transition delay={1000 + index * 100} key={index} duration={1000}>
									<Button.Outline href={action.href}>
										{action.icon}
										<ActionText>{action.text}</ActionText>
									</Button.Outline>
								</Transition>
							);
						})}
					</Actions>
				</Content>
			</Container>
		</Layout.Default>
	);
}
