// components/Blog/Post.component.tsx
import Link from 'next/link';
import styled from '@emotion/styled';
import tw from 'twin.macro';

import { Blog } from '..';

import type { FrontMatter } from '~/types';

interface PostProps {
	index: number;
	frontmatter: FrontMatter;
}

const Container = styled.a(tw`
	flex flex-col \
	bg-white bg-opacity-75 dark:bg-gray-900 dark:bg-opacity-75 \
	backdrop-filter backdrop-blur-sm \
	rounded-2xl overflow-hidden hover:shadow-xl cursor-pointer \
	transform hover:-translate-y-1 \
	transition ease-in-out duration-300 \
	focus:outline-none focus:ring-4 focus:ring-offset-8 focus:ring-primary-500
`);

const Banner = styled.div`
	${tw`
		relative flex justify-center my-auto \
			w-full max-w-xl \
			overflow-hidden
	`}

	img {
		${tw`
			absolute top-0 left-0 w-full h-48 \
				object-cover select-none
		`}
	}
`;

const BannerPlaceholder = styled.div(tw`
	w-full h-full lg:h-48 \
	bg-gray-200 dark:bg-gray-600
	animate-pulse
`);

const Content = styled.div(tw`
	flex-1 flex flex-col justify-between \
	p-6 \
	bg-transparent \
	rounded-2xl lg:rounded-tr-none lg:rounded-tl-none \
	border-2 lg:border-t-0 border-gray-100 dark:border-gray-500 \
	bg-transparent
`);

const ContextText = styled.div(tw`
	flex flex-col flex-1 justify-around \
	rounded-lg \
	text-gray-300 dark:text-gray-400 \
	focus:outline-none focus:ring-4 focus:border-none focus:ring-primary-500
`);

const Title = styled.p(tw`
	text-xl font-bold \
	text-gray-900 dark:text-gray-100
`);

const Description = styled.p(tw`
	mt-3 \
	text-base line-clamp-2
`);

const Footer = styled.div(tw`
	flex items-start space-x-1 \
	mt-4 \
	text-sm
`);

export function _Post({ index, frontmatter }: PostProps) {
	return (
		<Link
			aria-label={`Read blog post: ${frontmatter.title}`}
			href={`/blog/${frontmatter.slug}`}>
			<Container>
				{frontmatter.banner && index <= 2 && (
					<Banner>
						<BannerPlaceholder />
						<img
							alt={frontmatter.title}
							draggable={false}
							loading="lazy"
							src={frontmatter.banner}
						/>
					</Banner>
				)}

				<Content>
					<ContextText>
						<Title>{frontmatter.title}</Title>
						{((frontmatter.description && frontmatter.description_show) || true) && (
							<Description aria-label={frontmatter.description}>
								{frontmatter.description}
							</Description>
						)}
						<Footer>
							<Blog.Date>{frontmatter.date}</Blog.Date>
						</Footer>
					</ContextText>
				</Content>
			</Container>
		</Link>
	);
}

// src/components/blog/Post.vue
<template>
	<div class="content">
		<div v-if="frontmatter.banner" class="banner">
			<div class="relative" v-if="frontmatter.banner_show || true">
				<div class="placeholder animate-pulse" />

				<template v-if="Array.isArray(frontmatter.banner)">
					<picture>
						<img
							v-for="(src, i) in frontmatter.banner.reverse()"
							:key="i"
							:src="src"
							:alt="frontmatter.banner_alt ?? frontmatter.title"
							:draggable="false"
						/>
					</picture>
				</template>
				<template v-else>
					<img
						:src="frontmatter.banner"
						:alt="frontmatter.banner_alt ?? frontmatter.title"
						:draggable="false"
					/>
				</template>
			</div>
		</div>

		<div class="body">
			<h1>
				<span
					v-if="frontmatter.title_prefix"
					class="prefix"
					v-text="frontmatter.title_prefix"
				/>
				<span v-if="frontmatter.title" class="title" v-text="frontmatter.title" />
			</h1>

			<p
				v-if="frontmatter.description_show ?? false"
				class="description"
				v-text="frontmatter.description"
			/>
		</div>
		<div class="body">
			<slot />
		</div>
	</div>
</template>

<script setup lang="ts">
import { useHead } from '@vueuse/head';
import { defineProps } from 'vue';

import type { IFrontmatter } from '~/types/blog';

const { frontmatter } = defineProps<{
	frontmatter: IFrontmatter;
}>();

useHead({
	title: `nuro ─ ${frontmatter.title || 'blog'}`,
});
</script>

<style lang="postcss" scoped>
.content {
	@apply relative mx-auto max-w-6xl px-4 py-16 sm:px-6 lg:px-8 \
		bg-gray-50 dark:bg-gray-900 bg-opacity-50 dark:bg-opacity-50 backdrop-filter backdrop-blur-sm \
		overflow-hidden;

	.banner {
		@apply sm:max-w-2xl lg:sm:max-w-6xl mx-auto;

		.placeholder {
			@apply w-full h-full h-[16rem] lg:h-lg mb-8 \
				bg-gray-200 dark:bg-gray-600 \
				rounded-4xl lg:rounded-6xl;
		}

		img {
			@apply absolute top-0 left-0 w-full h-auto max-h-[16rem] lg:max-h-lg \
				mb-8 \
				rounded-4xl lg:rounded-6xl object-cover select-none hover:shadow-xl \
				transition ease-in-out duration-300;
		}
	}

	.prefix {
		@apply block \
			text-base text-center font-semibold tracking-wide uppercase \
			text-primary-600;
	}

	.title {
		@apply block mt-2 \
			text-3xl sm:text-4xl text-center leading-8 font-extrabold tracking-tight \
			text-gray-900 dark:text-white;
	}

	.description {
		@apply mt-8 text-xl text-gray-400 leading-8;
	}

	.body {
		@apply mt-6 prose prose-primary prose-lg text-gray-500 mx-auto;
	}
}
</style>

<style lang="postcss">
.markdown-body {
	h1,
	h2,
	h3,
	h4,
	h5,
	h6 {
		@apply dark:text-white !important;

		&:hover,
		&:focus {
			.header-anchor {
				@apply opacity-100 no-underline;
			}
		}
	}

	a {
		@apply no-underline rounded \
				dark:text-white \
				transition duration-300 ease-in-out \
				focus:outline-none focus:ring-4 focus:ring-primary-500 focus:ring-offset-2 !important;
	}

	p,
	ul,
	li {
		@apply text-gray-400;
	}

	strong {
		@apply dark:text-white !important;
	}

	img {
		@apply rounded-3xl object-cover select-none hover:shadow-xl \
			transition ease-in-out duration-300;
	}

	figcaption {
		@apply text-gray-200 dark:text-gray-400 \
			text-center !important;
	}

	hr {
		@apply mb-8 dark:border-gray-600 !important;
	}

	p code {
		@apply mx-0.5 py-1 px-2 \
			bg-gray-900 dark:bg-gray-500 \
			text-gray-200 dark:text-gray-100 \
			rounded-lg !important;

		&:after,
		&:before {
			@apply hidden;
		}
	}

	th {
		@apply dark:text-white;
	}

	td {
		@apply dark:text-gray-400;
	}

	ol li::before {
		@apply dark:text-gray-300 !important;
	}
}

a.item {
	@apply opacity-60 no-underline border-b-0 \
			transition duration-200 ease-out;

	&:hover {
		@apply opacity-100;
	}
}

a.header-anchor {
	@apply float-left mt-0.5 -ml-5 pr-2 \
			border-none \
			opacity-0 no-underline;
}
</style>
