// src/components/Background.vue
<template>
	<div ref="background" class="background" />
</template>

<script lang="ts" setup>
import { useEventListener } from '@vueuse/core';
import { Color, Mesh, Program, Renderer, Triangle } from 'ogl-typescript';
import { onMounted, ref } from 'vue';

import VertexShader from '../assets/shaders/background.vs?raw';
import FragmentShader from '../assets/shaders/background.fs?raw';

const background = ref<HTMLDivElement | null>(null);
const renderer = new Renderer({
	dpr: 2,
	alpha: true,
});
const gl = renderer.gl;

onMounted(async () => {
	try {
		if (background.value) background.value.appendChild(gl.canvas);
	} catch (error) {
		return console.error(`Failed to append canvas to DOM: `, error);
	}

	gl.clearColor(1, 1, 1, 1);

	const resize = () => renderer.setSize(window.innerWidth, window.innerHeight * 0.75);
	useEventListener('resize', resize);
	resize();

	const geometry = new Triangle(gl);
	const program = new Program(gl, {
		vertex: VertexShader,
		fragment: FragmentShader,
		uniforms: {
			uTime: {
				value: 0,
			},
			uColor: {
				value: new Color(0.3, 0.2, 0.5),
			},
		},
	});
	const mesh = new Mesh(gl, {
		geometry,
		program,
	});

	const update = (t: number) => {
		requestAnimationFrame(update);
		program.uniforms.uTime.value = t * 0.001;
		renderer.render({
			scene: mesh,
		});
	};
	requestAnimationFrame(update);
});
</script>

<style lang="postcss" scoped>
.background {
	@apply fixed inset-0 -z-10;
}
</style>

// src/components/Background/index.tsx
'use client';

import FragmentShader from './fragment.glsl';
import VertexShader from './vertex.glsl';
import { Camera, Color, Geometry, Mesh, Program, Renderer } from 'ogl-typescript';
import { useEffectOnce } from 'react-use';
import { colors } from '~/tailwind.config';

export function Background(): null {
	useEffectOnce(() => {
		let animationId = 1;

		const renderer = new Renderer({
			depth: false,
			dpr: 2,
			alpha: true,
		});

		const gl = renderer.gl;

		const camera = new Camera(gl, {
			fov: 15,
		});
		camera.position.z = 15;

		function handleReisze(): void {
			renderer.setSize(window.innerWidth, window.innerHeight);
			camera.perspective({
				aspect: gl.canvas.width / gl.canvas.height,
			});
		}

		setTimeout(() => {
			try {
				gl.canvas.id = 'background';
				gl.canvas.classList.add(
					'-z-10',
					'animate-in',
					'duration-2000',
					'fade-in',
					'ease-bounce',
					'fixed',
					'inset-0',
					'zoom-in',
				);
				document.body.appendChild(gl.canvas);
				gl.clearColor(0, 0, 0, 0);
				window.addEventListener('resize', handleReisze, false);
				handleReisze();
			} catch (error) {
				console.error(error);
			}
		}, 500);

		const numParticles = 100;
		const position = new Float32Array(numParticles * 3);
		const random = new Float32Array(numParticles * 4);

		for (let i = 0; i < numParticles; i++) {
			position.set([Math.random(), Math.random(), Math.random()], i * 3);
			random.set([Math.random(), Math.random(), Math.random(), Math.random()], i * 4);
		}

		const geometry = new Geometry(gl, {
			position: {
				size: 3,
				data: position,
			},
			random: {
				size: 4,
				data: random,
			},
		});

		const program = new Program(gl, {
			vertex: VertexShader,
			fragment: FragmentShader,
			uniforms: {
				uTime: {
					value: 0,
				},
				uColor: {
					value: new Color(colors.gray[500]),
				},
			},
			transparent: true,
			depthTest: false,
		});

		const particles = new Mesh(gl, {
			mode: gl.POINTS,
			geometry,
			program,
		});

		function update(t: number): void {
			animationId = requestAnimationFrame(update);

			particles.rotation.z += 0.001;
			program.uniforms.uTime.value = t * 0.0001;

			renderer.render({
				scene: particles,
				camera: camera,
			});
		}
		animationId = requestAnimationFrame(update);

		return () => cancelAnimationFrame(animationId);
	});

	return null;
}
